# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set oh-my-zsh theme to oh-my-posh catpuccin mocha 
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/catppuccin_mocha.omp.json)"
fi

# Set zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# ZSH Plugins
plugins=(
  z
  git
  nvm
  brew
)

source $ZSH/oh-my-zsh.sh

# -------------------
# User Configurations
# -------------------

# Aliases
source $HOME/.dotfiles/zsh/aliases.zsh

# Go Path
export PATH=$PATH:$(go env GOPATH)/bin

# Android Development
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
