# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# ZSH Plugins
plugins=(
  z
  git
  nvm
  brew
)

source $ZSH/oh-my-zsh.sh

# Set oh-my-zsh theme to starship catpuccin mocha 
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(starship init zsh)"
fi

# -------------------
# User Configurations
# -------------------

# Aliases
source $HOME/.dotfiles/zsh/aliases.zsh

# Go Path
export PATH=$PATH:$(go env GOPATH)/bin

# Android Development
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# bun completions
[ -s "/Users/brendencroft/.bun/_bun" ] && source "/Users/brendencroft/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
